;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        cua-copy-handler
        cua-copy-region
        cua-cut-handler
        cua-cut-region
        cua-exchange-point-and-mark
        cua-paste
        eglot
        emt-backward-word
        emt-forward-word
        end-of-visual-line
        forward-sexp
        global-visual-line-mode
        hash--beginning-of-line
        hash--end-of-line
        kill-visual-line
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        ace-swap-window
        describe-key
        describe-variable
        ignore
        keyboard-escape-quit
        kill-region
        magit-blame
        magit-blame-addition
        mc/mark-next-lines
        mc/mark-previous-lines
        mouse-drag-mode-line
        mouse-select-window
        pixel-scroll-precision
        undo-redo
        whitespace-mode
        ))
